### PR TITLE
rename notebooks

### PR DESCRIPTION
**Pull request by rabernat**
This adds a title to the dask notebook and renames it.

### CODE REVIEW

**Comment by rabernat** [comment]
cc @TomAugspurger

**Comment by TomAugspurger** [comment]
Beat me to it :)

Would detecting this in CI need a change in binderbot to ensure that the notebook starts with a title?

**Comment by rabernat** [comment]
> Would detecting this in CI need a change in binderbot to ensure that the notebook starts with a title?

Yes, I would love to add a notebook linter which does a few things:
- checks that there is a valid title, using the same logic as nbsphinx
- applies black to the code cells
- clears any output cells
- generates a thumbnail automatically if it is not present
- commits all of these changes automatically to any PRs

**Comment by rabernat** [comment]
FYI, the built gallery is here: http://gallery.pangeo.io/repos/pangeo-gallery/example-gallery/index.html

**Pull request merged**
